# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

# Dependencies
before_install:
  - composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source

script: phpunit

# Cache dependencies
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
