# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

# Dependencies
install:
  - composer self-update
  - travis_retry composer update --no-interaction --prefer-source --dev $PREFER_LOWEST

script: phpunit

# Cache dependencies
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
